### ISSUE TITLE
Need to add `id` and `label` fields to all CWL's and tools

### ISSUE THREAD

**Issue by stevekm** [mskcc/pluto-cwl#114]
All workflows, subworkflows, and `CommandLineTool`'s (and other tools and workflow processes) should be tagged with labels like this;

```
vcf_to_maf:
    run:
        class: CommandLineTool
        id: vcf_to_maf
        label: vcf_to_maf
```

This will make the logs easier to parse in order to track the status of workflow tasks. Otherwise workflow tasks seem to be represent in logs with uninterpretable hash ID's that are largely impossible to trace back to any discernible CWL component. For some reason, both `id` and `label` fields are required, having only one of them does not propagate them into the logs.

These fields can be seen with the `toil_track_utils.py` script (https://github.com/mskcc/pluto/blob/master/toil_track_utils.py)
